services:
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
      #- /home/node/app/node_modules - volume anonimo
  
  db:
    image: mysql:8.0.30-debian
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=nest
    volumes:
      - ./.docker/dbdata:/var/lib/mysql